// Lista de cantantes extraída de 1cantantes.txt
const CANTANTES_DATA = [
  "Abel Zabala",
  "Adrian Juniors",
  "Alex Campos",
  "Alex Zurdo",
  "Almigthy",
  "Barak",
  "Christine D Clario",
  "Daddy Yankee",
  "Daniel Calveti",
  "Danilo Montero",
  "David Quindal",
  "En Espiritu y En Verdad",
  "Farruko",
  "Funky",
  "Generacion 12",
  "Helen D La Roca",
  "Hillsong",
  "Jaime Murrell",
  "Jesus Adrian Romero",
  "Juan Luis Guerra",
  "Julio Melgar",
  "Julissa",
  "Kike Pavon",
  "Marcela Gandara",
  "Marcos Barrientos",
  "Marcos Brunet",
  "Marcos Witt",
  "Marcos Yaroide",
  "Miel San Marcos",
  "Nancy Amancio",
  "New Wine",
  "Rabito",
  "Redimidos",
  "Rescate",
  "Rey de Reyes",
  "Rojo",
  "Samuel Hernandez",
  "Seth Condney",
  "Tercer Cielo",
  "Uncion Tropical",
  "Vico C"
];
